blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/lwshakib/imemo-smart-clipboard/discussions
    about: Please ask questions and share ideas in our GitHub Discussions.
